/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by hbm2java", 0)}
 */

<#assign idType = pojo.getJavaTypeName(pojo.getIdentifierProperty(),false)/>
<#include "OracleCheck.ftl" />
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} extends <#if useOracle>com.solace.data.Entity<${idType}><#else>IdentityEntity<${idType}></#if>
