/*******************************************************************************
 * Copyright (c) 2013 <a href="mailto:daniel.williams@gmail.com">Daniel Williams</a>.
 * All rights reserved. This program, solace.common, and file, ObjectFactory.java, and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 * 
 * Contributors:
 *     <a href="mailto:daniel.williams@gmail.com">Daniel Williams</a> - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.09 at 02:30:27 PM EDT 
//


package com.solace;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.solace package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.solace
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExceptionHandlers.Target.Handler }
     * 
     */
    public ExceptionHandlers.Target.Handler createExceptionHandlersTargetHandler() {
        return new ExceptionHandlers.Target.Handler();
    }

    /**
     * Create an instance of {@link ExceptionHandlers.Default }
     * 
     */
    public ExceptionHandlers.Default createExceptionHandlersDefault() {
        return new ExceptionHandlers.Default();
    }

    /**
     * Create an instance of {@link ExceptionHandlers.Target }
     * 
     */
    public ExceptionHandlers.Target createExceptionHandlersTarget() {
        return new ExceptionHandlers.Target();
    }

    /**
     * Create an instance of {@link ExceptionHandlers }
     * 
     */
    public ExceptionHandlers createExceptionHandlers() {
        return new ExceptionHandlers();
    }

}
