/*******************************************************************************
 * Copyright (c) 2013 <a href="mailto:daniel.williams@gmail.com">Daniel Williams</a>.
 * All rights reserved. This program, solace.common, and file, ObjectFactory.java, and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 * 
 * Contributors:
 *     <a href="mailto:daniel.williams@gmail.com">Daniel Williams</a> - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.21 at 06:37:52 PM EDT 
//


package com.solace.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.solace.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.solace.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Databases.DatabaseConfig.Pooling }
     * 
     */
    public Databases.DatabaseConfig.Pooling createDatabasesDatabasePooling() {
        return new Databases.DatabaseConfig.Pooling();
    }

    /**
     * Create an instance of {@link Databases.DatabaseConfig.Auth }
     * 
     */
    public Databases.DatabaseConfig.Auth createDatabasesDatabaseAuth() {
        return new Databases.DatabaseConfig.Auth();
    }

    /**
     * Create an instance of {@link Databases.DatabaseConfig }
     * 
     */
    public Databases.DatabaseConfig createDatabasesDatabase() {
        return new Databases.DatabaseConfig();
    }

    /**
     * Create an instance of {@link Databases.DatabaseConfig.Handler }
     * 
     */
    public Databases.DatabaseConfig.Handler createDatabasesDatabaseHandler() {
        return new Databases.DatabaseConfig.Handler();
    }

    /**
     * Create an instance of {@link Databases.DatabaseConfig.Handler.Property }
     * 
     */
    public Databases.DatabaseConfig.Handler.Property createDatabasesDatabaseHandlerProperty() {
        return new Databases.DatabaseConfig.Handler.Property();
    }

    /**
     * Create an instance of {@link Databases }
     * 
     */
    public Databases createDatabases() {
        return new Databases();
    }

    /**
     * Create an instance of {@link Databases.DatabaseConfig.Timeout }
     * 
     */
    public Databases.DatabaseConfig.Timeout createDatabasesDatabaseTimeout() {
        return new Databases.DatabaseConfig.Timeout();
    }

}
